Minify refactor
caleb531/automata pull request #77
Opened 2022-10-23 03:52 UTC by eliotwrobson

@caleb531 Refactors the minify and cross product functions to avoid creating intermediate DFAs. Cross product function now returns only reachable part of the product DFA by default.

2022-10-23 04:00 UTC, caleb531 requested changes
@eliotwrobson Looks good so far, although there are a few `filter` calls that I would prefer to have written as set comprehensions.

2022-10-23 04:20 UTC, eliotwrobson commented on automata/fa/dfa.py
> +                reachable_final_states=set(filter(union_fn, new_states)),
@caleb531 done!

2022-10-23 17:00 UTC, eliotwrobson commented
@caleb531 needs a rebase after merging my other PR, but should be good to go otherwise.

2022-10-24 01:22 UTC, Tagl approved these changes
Looks good

2022-10-25 23:25 UTC, caleb531 commented on automata/fa/dfa.py
> +    def from_nfa(cls, target_nfa, *, retain_names=False, minify=True):
@eliotwrobson Just want to say good idea to make these keyword-only arguments 🙂

2022-10-25 23:26 UTC, caleb531 commented
@eliotwrobson This looks great! Will approve and merge now. Thank you for this!

2022-10-25 23:27 UTC, caleb531 approved these changes

2022-10-25 23:27 UTC, merged

2022-10-25 23:42 UTC, caleb531 commented
@eliotwrobson I noticed there's a partial branch on one of the `_minify` lines when I run the coverage report:

<img width="1159" alt="Screen Shot 2022-10-25 at 4 28 53 PM" src="https://user-images.githubusercontent.com/872474/197901956-1bf80740-608b-4ad2-9403-d3e40376bafb.png">

To solve this (i.e. bring the coverage back to 100%), is this just as simple as me minifying a DFA with at least one unreachable state?

2022-10-25 23:45 UTC, eliotwrobson commented
@caleb531 I think that's correct. Now that the other functions that were calling minify only generate reachable states by default, it's not getting hit. You can probably just add an extra dummy state to one of the tests for minify.